final_request: "Finalement je veux separer le fichier de config user et le fichier project instruction + codebase context. 
donne le code complet pour faire en sorte que la modification soit bien prise en compte"