# Liste des patterns de fichiers/extensions à ignorer
ignore_patterns:
  - "*.log"
  - "*.logs" 
  - "*.jpg"
  - "*.jpeg"
  - "*.png"
  - "*.gif"
  - "*.svg"
  - "*.ico"
  - "*.bmp"
  - "*.tiff"
  - "*.webp"
  - "*.mp3"
  - "*.wav"
  - "*.mp4"
  - "*.avi"
  - "*.mov"
  - "*.zip"
  - "*.tar"
  - "*.gz"
  - "*.7z"
  - "*.rar"
  - "*.pdf"
  - "*.doc"
  - "*.docx"
  - "*.xls"
  - "*.xlsx"
  - "*.ppt"
  - "*.pptx"
  - "*.exe"
  - "*.dll"
  - "*.so"
  - "*.o"
  - "*.a"
  - "*.class"
  - "*.jar"
  - "*.war"
  - "*.ear"
  - "*.pyc"
  - "*.pyo"
  - "*.pyd"
  - "*.db"
  - "*.sqlite"
  - "*.sqlite3"
  - "*.db3"
  - "*.sql"
  - "*.bak"
  - "*.tmp"
  - "*.temp"
  - "*.swp"
  - "*.swo"
  - "*.DS_Store"
  - "*.idea"
  - "*.vscode"
  - "*.git"
  - "*.svn"
  - "*.hg"
  - "*.bzr"
  - "*.env"
  - "*.env.*"
  - "*.csv"