project_name: "Immersive Try-On Kiosk"

objectives:
  - "Provide an immersive and fluent user experience to virtually try on clothing."
  - "Ensure a complete workflow: from initial photo capture to generating multiple try-on images."
  - "Facilitate easy addition of new clothing categories, items, and languages."

code_conventions:
  language_stack:
    frontend: "React (ESModules, functional components)"
    backend: "Node.js / Express"
  directories_structure:
    frontend: "src/components, src/pages, src/services, src/styles"
    backend: "src/routes, src/controllers, src/models, src/services"
  coding_style:
    - "Follow ES6 conventions"
    - "Write clean, well-commented, and readable code"
    - "Separate business logic from presentation"
    - "Use hooks and context for state management if necessary"

privacy_and_legal:
  - "Obtain explicit consent before capturing and saving photos"
  - "Save each session and its associated images in the database"
  - "No reuse of images outside the current session"

performance_and_architecture:
  - "Image generation should take between 5s and 1min max"
  - "Only one user session at a time"
  - "Maintain a clean, modular, and maintainable codebase"

ux_guidelines:
  - "Fullscreen interface without global scroll"
  - "Smooth navigation, visual and audio feedback"
  - "Large buttons, clear text"
  - "On-the-fly language switching"
  - "Scrollable sidebars for history and item selection"

advertising:
  - "Display a non-intrusive ad during image generation"

evolutivity:
  - "Add new categories, items, and languages easily"
  - "Maintain a code structure that supports future extensions"
