source_directory: /home/ilan/code/ai-promp-tool
exclude_patterns:
  - data
  - .git
  - .github
  - .vscode
  - .idea
  - .husky
  - venv
  - node_modules
  - dist
  - build
  - coverage
  - .cache
  - out
  - '*.log'
  - .DS_Store
  - Thumbs.db
  - .env
  - .env.*
  - yarn.lock
  - package-lock.json
  - '*.tmp'
  - '*.bak'
  - '*.swp'
selected_project_data: project_data.yaml
selected_user_config: user_config.yaml
selected_files:
  - config/final_request.yaml
  - config/formats
  - config/formats/automatic_xml.txt
  - config/formats/diff.txt
  - config/formats/gpt.txt
  - config/formats/json.txt
  - config/formats/markdown.txt
  - config/formats/none.txt
  - config/formats/structured.txt
  - config/formats/xml.txt
  - config/templates
  - config/templates/example_user_config.yaml
  - config/user_config.yaml
