source_directory: /home/ilan/code/ai-promp-tool
exclude_patterns:
  - data
  - .git
  - .github
  - .vscode
  - .idea
  - .husky
  - venv
  - node_modules
  - dist
  - build
  - coverage
  - .cache
  - out
  - '*.log'
  - .DS_Store
  - Thumbs.db
  - .env
  - .env.*
  - yarn.lock
  - package-lock.json
  - '*.tmp'
  - '*.bak'
  - '*.swp'
selected_project_data: user_config.yaml
selected_user_config: user_config.yaml
selected_files:
  - README.md
  - config
  - config/final_request.yaml
  - config/formats
  - config/formats/diff.xml
  - config/formats/gpt.xml
  - config/formats/json.xml
  - config/formats/markdown.xml
  - config/formats/none.xml
  - config/formats/xml.xml
  - config/templates
  - config/templates/example_user_config.yaml
  - config/user_config.yaml
  - package.json
  - perso
  - perso/projet_instruction.md
  - run_full_process.sh
  - scripts
  - scripts/apply_diff.py
  - scripts/generate_prompt.py
  - scripts/generate_structure.py
  - server.js
  - templates
  - templates/prompt_template.xml.jinja2
  - web_ui
  - web_ui/components
  - web_ui/components/DirectoryModal.js
  - web_ui/components/FileTree.js
  - web_ui/components/Navigation.js
  - web_ui/configuration.html
  - web_ui/diff.html
  - web_ui/index.html
  - web_ui/services
  - web_ui/services/api.js
  - web_ui/services/state.js
  - web_ui/styles
  - web_ui/styles/components
  - web_ui/styles/components/directory-modal.css
  - web_ui/styles/components/file-tree.css
  - web_ui/styles/components/navigation.css
  - web_ui/styles/main.css
  - web_ui/utils
  - web_ui/utils/common.js
