source_directory: /home/ilan/code/youtubeFactCheck
exclude_patterns:
  - data
  - .git
  - .github
  - .vscode
  - .idea
  - .husky
  - venv
  - node_modules
  - dist
  - build
  - coverage
  - .cache
  - out/
  - '*.log'
  - .DS_Store
  - Thumbs.db
  - .env
  - .env.*
  - yarn.lock
  - package-lock.json
  - '*.tmp'
  - '*.bak'
  - '*.swp'
  - translations/*.json
  - translations/
selected_project_data: project_data.yaml
selected_user_config: user_config.yaml
selected_files:
  - backend/index.js
