source_directory: /home/ilan/code/try-on
exclude_patterns:
  - data
  - .git
  - .github
  - .vscode
  - .idea
  - .husky
  - venv
  - node_modules
  - dist
  - build
  - coverage
  - .cache
  - out
  - '*.log'
  - .DS_Store
  - Thumbs.db
  - .env
  - .env.*
  - yarn.lock
  - package-lock.json
  - '*.tmp'
  - '*.bak'
  - '*.swp'
selected_project_data: user_config.yaml
selected_user_config: user_config.yaml
selected_files:
  - configuration.js
  - diff.js
  - main.js
  - styles.css
  - config/final_request.yaml
  - config/formats
  - config/formats/diff.xml
  - config/formats/gpt.xml
  - config/formats/json.xml
  - config/formats/markdown.xml
  - config/formats/none.xml
  - config/formats/xml.xml
  - config/templates
  - config/templates/example_user_config.yaml
  - config/user_config.yaml
  - scripts/apply_diff.py
  - scripts/generate_prompt.py
  - scripts/generate_structure.py
  - templates/prompt_template.xml.jinja2
  - web_ui/components
  - web_ui/components/DirectoryModal.js
  - web_ui/components/FileTree.js
  - web_ui/components/Navigation.js
  - web_ui/configuration.html
  - web_ui/diff.html
  - web_ui/index.html
  - web_ui/services
  - web_ui/services/api.js
  - web_ui/services/state.js
  - web_ui/styles
  - web_ui/styles/components
  - web_ui/styles/components/directory-modal.css
  - web_ui/styles/components/file-tree.css
  - web_ui/styles/components/navigation.css
  - web_ui/styles/main.css
  - web_ui/utils
  - web_ui/utils/common.js
  - perso/projet_instruction.md
  - README.md
  - config
  - package.json
  - perso
  - run_full_process.sh
  - scripts
  - server.js
  - templates
  - web_ui
  - backend
  - backend/package.json
  - backend/prisma
  - backend/prisma/migrations
  - backend/prisma/migrations/20241210152450_init
  - backend/prisma/migrations/20241210152450_init/migration.sql
  - backend/prisma/migrations/migration_lock.toml
  - backend/prisma/schema.prisma
  - backend/src
  - backend/src/middleware
  - backend/src/middleware/upload.js
  - backend/src/prismaClient.js
  - backend/src/server.js
  - backend/src/services
  - backend/src/services/replicateService.js
  - frontend
  - frontend/README.md
  - frontend/package.json
  - frontend/public
  - frontend/public/index.html
  - frontend/src
  - frontend/src/App.js
  - frontend/src/components
  - frontend/src/components/FileInput.js
  - frontend/src/components/ImageDisplay.js
  - frontend/src/index.js
  - frontend/src/pages
  - frontend/src/pages/MainScreen.js
  - frontend/src/pages/PhotoConfirmationScreen.js
  - frontend/src/pages/TestPage.js
  - frontend/src/pages/WebcamScreen.js
  - frontend/src/styles
  - frontend/src/styles/App.css
  - frontend/src/styles/MainScreen.css
  - frontend/src/styles/PhotoConfirmationScreen.css
  - frontend/src/styles/WebcamScreen.css
  - frontend/src/styles/components.css
  - frontend/src/styles/global.css
  - prisma
  - migrations
  - 20241210152450_init
  - migration.sql
  - migration_lock.toml
  - schema.prisma
  - src
  - middleware
  - upload.js
  - prismaClient.js
  - services
  - replicateService.js
  - public
  - index.html
  - App.js
  - components
  - FileInput.js
  - ImageDisplay.js
  - index.js
  - pages
  - MainScreen.js
  - PhotoConfirmationScreen.js
  - TestPage.js
  - WebcamScreen.js
  - styles
  - App.css
  - MainScreen.css
  - PhotoConfirmationScreen.css
  - WebcamScreen.css
  - components.css
  - global.css
