instructions:
  - "Use XML tags to structure your response."
  - "Use `<code>` elements for code samples."
examples:
  - "<example>"
  - "  <title>Title</title>"
  - "  <list>"
  - "    <item>Bullet point</item>"
  - "  </list>"
  - "</example>"
